#!/bin/bash
LOG=/var/log/skripte/email.log
DATE=$(date "+%d.%m.%Y")
TIME=$(date "+%H:%M Uhr")
EMAIL="sandro.isoletta@gmx.de"

# Funktion für das Senden von Informations-E-Mails
infomail() {
	SKRIPT="${1}"
	OUTPUT="${2}"
	SUBJECT="Info: ${SKRIPT} wurde erfolgreich am $DATE um $TIME ausgeführt"
	echo -e "Das Skript ${SKRIPT} wurde erfolgreich am $DATE um $TIME ausgeführt. \n\nOUTPUT: ${OUTPUT}" | mail -s "${SUBJECT}" "${EMAIL}"
	echo -e "Das Skript ${SKRIPT} wurde erfolgreich am $DATE um $TIME ausgeführt. \n\nOUTPUT: ${OUTPUT}" | tee -a $LOG
}

# Funktion für das Senden von Warn-E-Mails
warnmail() {
	SKRIPT="${1}"
	OUTPUT="${2}"
	SUBJECT="WARNUNG: ${SKRIPT} wurde am $DATE um $TIME mit Fehlern beendet"
	echo -e "Das Skript ${SKRIPT} wurde am $DATE um $TIME mit einem Fehler beendet. \n\nOUTPUT: ${OUTPUT}." | mail -s "${SUBJECT}" "${EMAIL}"
	echo -e "Das Skript ${SKRIPT} wurde am $DATE um $TIME mit einem Fehler beendet. \n\nOUTPUT: ${OUTPUT}." | tee -a $LOG
}
