#!/bin/bash

if [ "$1" == "d" ]; then
        echo Ordner umbenennen
        # find "${PWD}" -type d -depth -exec rename -n 's/\s/_/g' {} \;
        # find "${PWD}" -type f -exec rename -n 's/\s/_/g' {} \;
	find "${PWD}" -depth -name "* *" -type d | while IFS= read -r dir
		do
			mv -v "$dir" "$(dirname "$dir")/$(basename "$dir"| tr ' ' _)"
		done
else
        # Umbenennung
        echo Dateien umbenennen
        # find "${PWD}" -depth -type d -exec rename 's/\s/_/g' {} \;
        # find "${PWD}" -type f -exec rename 's/\s/_/g' {} \;
	find "${PWD}" -depth -name "* *" -type f | while IFS= read -r dir
		do
			mv -v "$dir" "$(dirname "$dir")/$(basename "$dir"| tr ' ' _)"
		done
fi
