#!/bin/bash

USER=nextcloud
PW=Streuner!79
DB=nextcloud
logfile=/var/log/cronjobs/nextcloud_bruteforce.log

mysql -u$USER -p$PW -D $DB -e "select * from oc_bruteforce_attempts" | tee -a $logfile
mysql -u$USER -p$PW -D $DB -e "delete from oc_bruteforce_attempts where action='login'" | tee -a $logfile
