#!/bin/bash

QUELLE1=/home/sandro/nextcloud/Share/Naturdokumentation/RL
QUELLE2=/home/sandro/nextcloud/Share/Naturdokumentation/Hentai
ZIEL1=/media/HDD4/Natur/Knast
ZIEL2=/media/HDD4/Natur/Hentai/Knast

sudo mv $QUELLE1/* $ZIEL1/
sudo mv $QUELLE2/* $ZIEL2/

sudo chown -R nas:users /media/HDD4/Natur
