#!/bin/bash
clear

check=1

while [ $check = 1 ]; do
	if [ -n "$error" ]; then
		echo -e "\033[31m$error\033[0m"
	fi

	echo
	echo "1: Start Tailscale"
	echo "2: Stop Tailscale"
	echo "3: Login Tailscale"
	echo "4: Logout Tailscale"
	echo "5: Tailscale Status"
	echo "6: Tailscale installieren"
	echo "7: Tailscale deinstallieren"
	echo "8: Tailscale Server einrichten"
	echo
	read -p "Eingabe: " cmd
	cmd=${cmd,,}

	case $cmd in

		1)
			echo 
			 tailscale up --accept-routes
			check=0
			;;
		2)
			echo
			 tailscale down
			check=0
			;;
		3)
			echo
			 tailscale login
			check=0
			;;
		4)
			echo
			 tailscale logout
			check=0
			;;
		5)
			echo
			 tailscale status
			check=0
			;;
		6)
			echo
			 curl -fsSL https://tailscale.com/install.sh | sh
			check=0
			;;
		7)
			echo
			REMOVE=$(dpkg -l | grep tailscale | awk '{print $2}');  apt-get remove --purge $REMOVE
			check=0
			;;
		8)
			echo
			read -p "Welches Subnetz soll geroutet werden? (bsp. 192.168.79.0/24)" cmd
			tailscale up --advertise-routes=$cmd
			check=0
			;;			
		quit)
			echo
			echo "Programm wird beendet"
			echo
			exit 0;
			;;
		exit)
			echo
			echo "Programm wird beendet"
			echo
			exit 0;
			;;
		*)
			echo
			error='Fehlerhafte Eingabe - Bitte 1, 2 oder 3 wählen'
			check=1
		esac
	done


echo Fertig
exit 0;
