#!/bin/bash
clear

# Noch einbauen
# folder=(a b c d)
# for i in ${folder[@]}; do

#        echo "$i wird nach ${bak}${i} gepackt" | tee -a $logfile
#        tar -czf ${i}_${d}.tar.gz /var/www/${i} | tee -a $logfile
#        echo
# done


for_a-z() {
	# Gebe alle Buchstaben von A bis Z aus
	clear
	echo "Gebe alle Buchstaben von A bis Z aus"
	echo "------------------------------------"
	echo	
	echo "Befehl: for i in {A..Z}; do echo $i; done"
	echo 
	echo
	for i in {A..Z}; do echo $i; done
	echo
}

for_one2ten() {
	# Führe 10 mal den Befehl echo "Hallo Welt!" aus
	clear
	echo "Führe 10 mal den Befehl echo 'Hallo Welt!' aus"
	echo "----------------------------------------------"
	echo
	echo "Befehl: for i in {1..10}; do echo "Hallo Welt!"; done"
	echo
	echo
	X=1
	for i in {1..10}; do echo "${X}.) Hallo Welt!"; ((X=$X+1)); done
	echo
}

for_one2x() {
	# Führe x-mal den Befehl echo "Hallo Welt!" aus
	clear
	echo "Führe X-mal den Befehl echo 'Hallo Welt!' aus"
	echo "---------------------------------------------"
	echo
	echo "Befehl: for i in \$(eval echo "{\$START..\$ENDE}"); do echo "Hallo Welt!"; done"
	echo
	read -p "Wie weit soll gezählt werden? " ENDE
	echo

	START=1
	X=${START}
	
	for i in $(eval echo "{$START..$ENDE}"); do echo "${X}.) Hallo Welt!";((X=$X+1)); done
	echo
}

countdown() {
	# Führe einen Countdown aus
	clear
	echo "Führe einen Countdown aus"
	echo "-------------------------"
	echo
	read -p "Wie weit soll ich zählen? " END
	echo

	START=1

	echo "-----------"
	echo "-Countdown-"
	echo "-----------"
 
	for (( c=$START; c<=$END; c++ ))
		do
			echo -n "$c "
			sleep 1
		done
 	echo
	echo "-----------"
	echo "-  Boom!  -"
	echo "-----------"
	echo 
}

while_file() {
	clear
	echo "Diese While-Schleife liest die Datei while_schleife.txt und gibt Zeile für Zeile aus"
	echo "Code:"
	echo "while read CMD; do echo \$CMD; done < "while_schleife.txt""
	echo

	FILE=while_schleife.txt

	while read CMD; do
		echo "$CMD"
	done < "$FILE"
}


check=1

while [ $check = 1 ]; do
	if [ -n "$error" ]; then
		echo -e "\033[31m$error\033[0m"
	fi

	echo
	echo "Bitte Programm wählen:"
	echo "----------------------"
	echo
	echo "============="
	echo "For-Schleifen"
	echo "============="
	echo
	echo "0) Ende"
	echo "1) Countdown"
	echo "2) Buchstaben von A bis Z ausgeben"
	echo "3) Führe 10 mal den Befehl echo 'Hallo Welt!' aus"
	echo "4) Führe X mal den Befehl echo 'Hallo Welt!' aus"
	echo 
	echo "==============="
        echo "While-Schleifen"
        echo "==============="
        echo
	echo "5) Datei Zeilenweise auslesen"
	echo
	read -p "Ihre Auswahl: " cmd
	cmd=${cmd,,}

	case $cmd in

		1)
			countdown
			check=0
			;;
		2)
			for_a-z
			check=0
			;;
		3)
			for_one2ten
			check=0
			;;
		4)
			for_one2x
			check=0
			;;
		0)
			echo
			echo "Programm wird beendet"
			echo
			exit 0;
			;;
		5)
			while_file
			check=0
			;;
		q)
			echo
			echo "Programm wird beendet"
			echo
			exit 0;
			;;
		end)
			echo
			echo "Programm wird beendet"
			echo
			exit 0;
			;;
		quit)
			echo
			echo "Programm wird beendet"
			echo
			exit 0;
			;;
		exit)
			echo
			echo "Programm wird beendet"
			echo
			exit 0;
			;;
		*)
			echo
			clear
			error='Fehlerhafte Eingabe - Bitte eine Zahl von 1 bis 5 wählen'
			check=1
		esac
	done


echo Ende des Programms
echo
exit 0;
