#!/bin/bash
clear
echo "Dieses Shell Skript testet, ob die BASH von einer Sicherheitslücke, welche Ende September 2014 bekannt wurde, betroffen ist."
echo "============================================================================================================================"
echo "       "
echo "Funktionsweise: Wenn der Schriftzug 'Gehackt' erscheint, dann ist die Bash angreifbar. Wenn nicht, so wurde die Lücke geschlossen."
echo "       "
echo "Test 1:"
echo "-------"
echo "       "
test="() { echo Hello; }; echo Gehackt" bash -c ""
echo "       "
echo "       "
echo "Test 2:"
echo "-------"
echo "       "
env x='() { :;}; echo Gehackt' bash -c "echo this is a test"
echo "       "
echo "       "
echo "Test 3:"
echo "-------"
echo "       "
env X='() { (a)=>\' bash -c "echo cat /etc/passwd"; cat echo
echo "       "
echo "       "
echo " ========================================================================================================================== "
echo "|                                                                                                                          |"
echo "|                                                     Bash Test beendet.                                                   |"
echo "|                                                                                                                          |"
echo " ========================================================================================================================== "
echo "       "
echo "       "
echo "       "
