#!/bin/bash

d=`date +%d.%m.%y`
t=`date +%H:%M_Uhr`

USER=nextcloud
PW=Streuner!79
DB=nextcloud
logfile=/var/log/cronjobs/nextcloud_bruteforce.log

echo "Ausführung am $d um $t" | tee -a $logfile
echo "--------------------------------------" | tee -a $logfile
mysql -u$USER -p$PW -D $DB -e "select * from oc_bruteforce_attempts" | tee -a $logfile
mysql -u$USER -p$PW -D $DB -e "delete from oc_bruteforce_attempts where action='login'" | tee -a $logfile
echo "" | tee -a $logfile

# echo "Nextcloud-Bruteforce Bereinigung wurde am $d um $t erfolgreich ausgeführt" | mailx -s "paqo.de cronjob 'Nextcloud-Bruteforce bereinigt am $d um $t'" sandro.isoletta@gmail.com
