#!/bin/bash
# pidof: 0 = läuft, 1 = läuft nicht


# if [ "$x" == "" ];
#	then
#		/home/sandro/bin/monerod
#	else
#		echo "Monero Dienst läuft." | mailx -s "paqo.de cronjob | Monero Dienst läuft." sandro.isoletta@gmail.com
#		exit
#fi


d=`date +%d.%m.%y`
t=`date +%H:%M`
x=`pidof monerod`;
SERVICE=monerod
EMAIL=sandro.isoletta@gmail.com
SCRIPT=/home/sandro/bin/monerod
LOG=/var/log/monero/monero_restart.log

if pgrep -x "$SERVICE" >/dev/null
	
	then
		echo "Monero Dienst läuft. Schicke jetzt ne Email!"
		echo "Monero Dienst läuft." | mail -s "paqo.de cronjob | Monero Dienst läuft." $EMAIL
	else
		echo "" | tee -a $LOG
		echo "Datum: $d" | tee -a $LOG
		echo "Uhrzeit: $t" | tee -a $LOG
		echo "" | tee -a $LOG
		echo "Monero-Daemon wurde beendet. Starte Prozess neu." | tee -a $LOG
	        $SCRIPT
		echo "" | tee -a $LOG
		echo "Monero Dienst wurde beendet. Versuche Prozess neu zu starten." | mail -s "paqo.de cronjob | Monero Dienst gestoppt." $EMAIL
fi
