#!/bin/bash
d=`date +%d.%m.%y`
t=`date +%H:%M`
x=`pidof monerod`;

SERVICE=monerod
EMAIL=sandro.isoletta@gmail.com
LOG=/var/log/cronjobs/monero_restart.log
PID=$(pgrep -x $SERVICE)

echo "Am $d um $t" | tee -a $LOG
echo "$SERVICE läuft als Prozess $PID" | tee -a $LOG
echo "Prozess wird beendet" | tee -a $LOG
kill -9 $PID | tee -a $LOG
pkill -9 $SERVICE | tee -a $LOG
echo "Monero Dienst wurde am $d um $t beendet." | mail -s "paqo.de cronjob | Monero Dienst gestoppt | $t" $EMAIL
