#!/bin/bash
d=`date +%d.%m.%y`
t=`date +%H:%M`
x=`pidof monerod`;

SERVICE=monerod
EMAIL=sandro.isoletta@gmail.com
SCRIPT=/home/sandro/bin/monerod
LOG=/var/log/cronjobs/monero_restart.log
PID=$(pgrep -x monerod)

if pgrep -x "$SERVICE" >/dev/null
	
	then
		kill -9 $PID
		echo "Am $d um $t" | tee -a $LOG
		echo "$SERVICE wird gestartet" | tee -a $LOG
		$SCRIPT | tee -a $LOG
		echo "Monero Dienst wurde am $d um $t gestartet." | mail -s "paqo.de cronjob | Monero Dienst start | $t" $EMAIL
	else
		echo "Am $d um $t" | tee -a $LOG
                echo "$SERVICE wird gestartet" | tee -a $LOG
	        $SCRIPT | tee -a $LOG
		echo "Monero Dienst wurde am $d um $t gestartet." | mail -s "paqo.de cronjob | Monero Dienst start | $t" $EMAIL
fi
