#! /bin/bash

EMAIL=sandro.isoletta@gmail.com

# Achtung:
# Noch nicht getestet

# Mit folgendem Skript sollen angeblich alle Emails von /var/mail/root verschickt werden

while IFS= read -r line; do
  echo "$line" | mail -s "Betreff" $EMAIL
done < /var/mail/root


# Sollte das nicht gehen, dann einfach mit
# echo 'd *' | mail -N
# alles löschen
